package com.example.alarmclock;

public class AlarmClockConstants {
    public static final String ALARM_CLOCK_START_RING_INTENT
            = "ALARM_CLOCK_START_RING_INTENT";
    public static final String ALARM_CLOCK_START_SNOOZE_INTENT
            = "ALARM_CLOCK_START_SNOOZE_INTENT";

    public static final String ALARM_CLOCK_SEND_INTENT_TO_RECEIVER_MINUTE_STRING
            = "ALARM_CLOCK_SEND_INTENT_TO_RECEIVER_MINUTE_STRING";
    public static final String ALARM_CLOCK_SEND_INTENT_TO_RECEIVER_HOUR_STRING
            = "ALARM_CLOCK_SEND_INTENT_TO_RECEIVER_HOUR_STRING";
    public static final String ALARM_CLOCK_SEND_INTENT_TO_RECEIVER_REPEATABILITY_STRING
            = "ALARM_CLOCK_SEND_INTENT_TO_RECEIVER_REPEATABILITY_STRING";
    public static final String ALARM_CLOCK_SEND_INTENT_TO_RECEIVER_SWITCH_ON_OFF_STRING
            = "ALARM_CLOCK_SEND_INTENT_TO_RECEIVER_SWITCH_ON_OFF_STRING";
    public static final String ALARM_CLOCK_SEND_INTENT_TO_RECEIVER_REQUEST_CODE_INT
            = "ALARM_CLOCK_SEND_INTENT_TO_RECEIVER_REQUEST_CODE_INT";

    public static final String ALARM_CLOCK_SEND_INTENT_FROM_RECEIVER_MINUTE_STRING
            = "ALARM_CLOCK_SEND_INTENT_FROM_RECEIVER_MINUTE_STRING";
    public static final String ALARM_CLOCK_SEND_INTENT_FROM_RECEIVER_HOUR_STRING
            = "ALARM_CLOCK_SEND_INTENT_FROM_RECEIVER_HOUR_STRING";
    public static final String ALARM_CLOCK_SEND_INTENT_FROM_RECEIVER_REPEATABILITY_STRING
            = "ALARM_CLOCK_SEND_INTENT_FROM_RECEIVER_REPEATABILITY_STRING";
    public static final String ALARM_CLOCK_SEND_INTENT_FROM_RECEIVER_SWITCH_ON_OFF_STRING
            = "ALARM_CLOCK_SEND_INTENT_FROM_RECEIVER_SWITCH_ON_OFF_STRING";
    public static final String ALARM_CLOCK_SEND_INTENT_FROM_RECEIVER_REQUEST_CODE_INT
            = "ALARM_CLOCK_SEND_INTENT_FROM_RECEIVER_REQUEST_CODE_INT";

    public static final String BOOT_COMPLETED = "android.intent.action.BOOT_COMPLETED";

    public static final int AMOUNT_OF_MINUTES_TO_SNOOZE_ALARM_CLOCK = 5;
}
